# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 19:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('printer', models.CharField(max_length=256)),
                ('copies', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=256)),
                ('charged_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
