# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170730_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=256)),
                ('paper_type', models.CharField(max_length=256, null=True)),
                ('price_per_sheet', models.IntegerField(null=True)),
                ('discount', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='brief',
            field=models.TextField(null=True),
        ),
    ]
