# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('app', '0004_auto_20170802_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='discount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='charged_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
             to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
