# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Paid', 'Paid')], max_length=256),
        ),
    ]
