# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170803_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='copies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='printer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Paid', 'Paid')], max_length=256),
        ),
    ]
